### ISSUE TITLE
Github Workflow doesn't work as expected.

### ISSUE THREAD

**Issue by bjompen** [PSBicep/PSBicep#225]
**Describe the bug**
Publish test result in p/r trigger crashes

**To Reproduce**
Create a p/r, watch the test result publisher not work.
Tests work as expected, and resultfile is found.

**Expected behavior**
The tests should pass so we can merge stuff.

**Comment by JohnRoos** [comment]
You could try to add continue-on-error to the publishh step in the workflow in your branch. This should allow the jobs to complete even if it fails to publish the result.

```yaml
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      continue-on-error: true
      with:
        files: testResults.xml
```
